---
- name: install CLI tools
  homebrew: name={{ item }} state=present
  with_items:
    - brew-cask
    - wget
    - heroku-toolbelt
    - android-sdk
    - autojump
    - zsh
    - gradle
    - postgresql
  when: ansible_os_family == 'Darwin'
